name: run code checks

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/Scony/godot-gdscript-toolkit.git

      - name: Run gdformat
        id: gdformat
        run: gdformat .

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push Changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'codeWonderland Bot'
          git config --global user.email 'development+bot@codewonder.land'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Fixing Formatting Issues"
          git push

      - name: Run gdlint
        run: gdlint .
